In [ ]:
import numpy as np
import cv2

In [ ]:
img_array = cv2.imread("/content/imresizer-test_image.png",cv2.IMREAD_GRAYSCALE)
test_array = img_array.reshape(1,784)
test_array

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [ ]:
hidden_layers=[64,64]

In [ ]:
np.random.randn(3,5)

array([[-0.1781261 , -2.69162829,  0.56181066,  0.15533306,  1.97351183],
       [ 1.15040649,  1.82648995, -0.63272295,  0.45905136,  0.57612883],
       [-0.12999036, -0.71787013, -0.31677494, -1.72159213, -1.42615457]])

In [ ]:
np.zeros((1,5))


array([[0., 0., 0., 0., 0.]])

In [ ]:
class Neural:
  def __init__(self,input_size=784,hidden_layers=[64,64],output_size=10):
    self.input_size = input_size
    self.hidden_layers = hidden_layers
    self.output_size = output_size
    self.weights = []
    self.biases = []

    #Input for hidden layers
    self.weights.append(0.01 * np.random.randn(input_size,hidden_layers[0]))
    self.biases.append(np.zeros((1,hidden_layers[0])))

    #Hidden Layers Network
    for i in range(len(hidden_layers)-1):
      self.weights.append(0.01 * np.random.randn(hidden_layers[i],hidden_layers[i+1]))
      self.biases.append(np.zeros((1,hidden_layers[i+1])))

    #Hidden layers to Output
    self.weights.append(0.01 * np.random.randn(hidden_layers[-1],output_size))
    self.biases.append(np.zeros((1,output_size)))

  def forward(self,inputs):
    layers = [inputs]
    #Dot product of inputs and weights
    for i in range(len(self.weights)):
      layers.append(np.dot(layers[-1],self.weights[i])+self.biases[i])
    return layers[-1]


In [ ]:
sample = np.random.rand(1,784)

In [ ]:
a = Neural()

In [ ]:
output = a.forward(inputs=test_array)
output

array([[ 0.10965255,  0.00331223, -0.03591428,  0.03061157, -0.14125132,
        -0.06938137,  0.17700021,  0.14117081,  0.14726304,  0.01170527]])